######################################################################
# Automatically generated by qmake (2.01a) Di. Okt 4 19:22:48 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += bezier.h gui.h spline_point.h
FORMS += gui.ui qtspline.ui
SOURCES += bezier.cpp gui.cpp main.cpp spline_point.cpp
