######################################################################
# Automatically generated by qmake (2.01a) Mi. Okt 5 16:04:24 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gui.h scene.h SpHook.h SpNode.h
FORMS += gui.ui
SOURCES += gui.cpp main.cpp scene.cpp SpHook.cpp SpNode.cpp
